Areas/Administration/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Grasshoppers.Data;
using Grasshoppers.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Grasshoppers.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class ItemsController: Controller
    {
        private readonly GrasshoppersContext _db;

        public ItemsController(GrasshoppersContext context)
        {
            _db = context;
        }
        
        private void PopulateOwners(int id)
        {
            var inventoryQuery = from invEntry in _db.Inventories where invEntry.ItemId == id
                orderby invEntry.Owner.Name
                select invEntry.Owner;
            
            ViewBag.Owners = inventoryQuery.AsNoTracking().ToList();
        }
        
        private void PopulateCharactersDropDownList(params object[] selectedCharacters)
        {
            var charactersQuery = from character in _db.Characters
                orderby character.Name
                select character;
            
            ViewBag.Characters = new MultiSelectList(charactersQuery.AsNoTracking(), "Id", 
                "Name", selectedCharacters);
        }
        
        public async Task<IActionResult> Index(int page = 1, int pageSize = 5)
        {
            return View(await PaginationViewModel<Item>.CreateAsync(_db.Items, page, pageSize));
        }
        
        [HttpPost]
        public async Task<IActionResult> Delete(IEnumerable<int> elems)
        {
            foreach (var curId in elems)
            {
                var item = await _db.Items.FirstOrDefaultAsync(it => it.Id == curId);

                if (item == null) continue;
                
                _db.Items.Remove(item);
                await _db.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }
        
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(Item item)
        { 
            _db.Items.Add(item);
            await _db.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            
            var item = await _db.Items.Include(it=>it.InventoryEntries)
                .ThenInclude(invEntry => invEntry.Owner)
                .FirstOrDefaultAsync(it => it.Id == id);

            if (item == null)
                return NotFound();
                    
            PopulateOwners((int)id);
            return View(item);
        }
        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            
            var item = await _db.Items.FirstOrDefaultAsync(it => it.Id == id);

            if (item == null)
                return NotFound();
            
            return View(item);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Item item)
        {
            _db.Items.Update(item);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Areas/Administration/Controllers/MapsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Grasshoppers.Data;
using Grasshoppers.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Grasshoppers.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class MapsController: Controller
    {
        private readonly GrasshoppersContext _db;

        public MapsController(GrasshoppersContext context)
        {
            _db = context;
        }
        
        private void PopulateMissions(int id)
        {
            var missionsQuery = from mission in _db.Missions where mission.MapId == id
                orderby mission.Name
                select mission;
            
            ViewBag.Missions = missionsQuery.AsNoTracking().ToList();
        }
        
        public async Task<IActionResult> Index(int page = 1, int pageSize = 5)
        {
            return View(await PaginationViewModel<Map>.CreateAsync(_db.Maps, page, pageSize));
        }
        
        [HttpPost]
        public async Task<IActionResult> Delete(IEnumerable<int> elems)
        {
            foreach (var curId in elems)
            {
                var map = await _db.Maps.FirstOrDefaultAsync(mp => mp.Id == curId);

                if (map == null) continue;
                
                _db.Maps.Remove(map);
                await _db.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }
        
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(Map map)
        { 
            _db.Maps.Add(map);
            await _db.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            
            var map = await _db.Maps.Include(mp=>mp.Missions)
                .FirstOrDefaultAsync(mp => mp.Id == id);

            if (map == null)
                return NotFound();
                    
            PopulateMissions((int)id);
            return View(map);
        }
        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            
            var map = await _db.Maps.FirstOrDefaultAsync(mp => mp.Id == id);

            if (map == null)
                return NotFound();
            
            return View(map);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Map map)
        {
            _db.Maps.Update(map);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Areas/Administration/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Grasshoppers.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Grasshoppers.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class RolesController:Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        
        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;

        }
        
        public async Task<IActionResult> Index(int page = 1, int pageSize = 5) => 
            View(await PaginationViewModel<IdentityRole>.CreateAsync(_roleManager.Roles, page, pageSize));
 
        public IActionResult Create() => View();
        
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (string.IsNullOrEmpty(name)) return View(name);
            
            var result = await _roleManager.CreateAsync(new IdentityRole(name));
            
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View();
        }
         
        [HttpPost]
        public async Task<IActionResult> Delete(IEnumerable<string> elems)
        {
            foreach (var curId in elems)
            {
                var role = await _roleManager.FindByIdAsync(curId);
            
                if (role != null)
                {
                    await _roleManager.DeleteAsync(role);
                }   
            }
            
            return RedirectToAction("Index");
        }
    }
}

Areas/Administration/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Grasshoppers.Areas.Administration.Models;
using Grasshoppers.Data;
using Grasshoppers.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Grasshoppers.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class UsersController : Controller
    {
        private readonly UserManager<User> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index(int page = 1, int pageSize = 5)
        {
            return View(await PaginationViewModel<User>.CreateAsync(_userManager.Users, page, pageSize));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(IEnumerable<string> elems)
        {
            var invokerUser = await _userManager.FindByNameAsync(User.Identity.Name);
            
            foreach (var curId in elems)
            {
                if (curId == invokerUser.Id) continue;
                
                var user = await _userManager.FindByIdAsync(curId);

                if (user != null)
                {
                    await _userManager.DeleteAsync(user);
                }   
            }

            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> ChangeRoles(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            
            var userRoles = await _userManager.GetRolesAsync(user);
            var allRoles = _roleManager.Roles.ToList();
            var model = new ChangeRoleViewModel
            {
                Id = user.Id,
                UserName = user.UserName,
                UserRoles = userRoles,
                AllRoles = allRoles
            };
            
            return View(model);
        }
        
        [HttpPost]
        public async Task<IActionResult> ChangeRoles(string id, List<string> roles)
        {
            var user = await _userManager.FindByIdAsync(id);
            
            if (user == null) return NotFound();
            
            var userRoles = await _userManager.GetRolesAsync(user);
                
            var addedRoles = roles.Except(userRoles);
                
            var removedRoles = userRoles.Except(roles);
 
            await _userManager.AddToRolesAsync(user, addedRoles);
 
            await _userManager.RemoveFromRolesAsync(user, removedRoles);
 
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_ActionBarPartial.cshtml
@{
    var controller = (string)ViewContext.RouteData.Values["controller"];
    var area = (string)ViewContext.RouteData.Values["area"];
}

<nav class="navbar navbar-expand-lg" style="background-color: lightsteelblue">
    
    <div class="container-fluid justify-content-start">
        
        <div class="navbar-brand">Actions:</div>
        
        <a asp-area="@area" asp-action="Create" asp-controller="@controller" 
                id="createButton" class="navbar-btn btn btn-success mr-3">Create</a>
        
        
        <form method="post" class="mr-auto" asp-area="@area" asp-action="Delete" asp-controller="@controller"
              id="deleteButton">
            <button type="submit" class="navbar-btn btn btn-danger mr-3">Delete</button>
        </form>

        <button id="btnExport" class="navbar-btn btn btn-info">Export to .xls</button>
    </div>

</nav>

Views/Shared/_AdminSidebarPartial.cshtml
<ul class="list-unstyled components">
    <li>
        <a href="#adminSubmenu" data-toggle="collapse" aria-expanded="false">Administration</a>
        <ul class="collapse list-unstyled" id="adminSubmenu">
            <li>
                <a asp-area="Administration" asp-controller="Users" asp-action="Index">Users</a>
            </li>
            <li>
                <a asp-area="Administration" asp-controller="Roles" asp-action="Index">Roles</a>
            </li>
        </ul>

        <a href="#entitiesSubmenu" data-toggle="collapse" aria-expanded="false">Grasshoppers entities</a>
        <ul class="collapse list-unstyled" id="entitiesSubmenu">
            <li>
                <a asp-area="Administration" asp-controller="Characters" asp-action="Index">Characters</a>
            </li>
            <li>
                <a asp-area="Administration" asp-controller="CharactersResults" asp-action="Index">Characters results</a>
            </li>
            <li>
                <a asp-area="Administration" asp-controller="GameSessions" asp-action="Index">Game sessions</a>
            </li>
            <li>
                <a asp-area="Administration" asp-controller="Inventories" asp-action="Index">Inventories</a>
            </li>
            <li>
                <a asp-area="Administration" asp-controller="Items" asp-action="Index">Items</a>
            </li>
            <li>
                <a asp-area="Administration" asp-controller="Maps" asp-action="Index">Maps</a>
            </li>
            <li>
                <a asp-area="Administration" asp-controller="Missions" asp-action="Index">Missions</a>
            </li>
        </ul>
    </li>
</ul>

Views/Shared/_CRUDPartial.cshtml
@using Microsoft.AspNetCore.Http
@{
    var controller = (string)ViewContext.RouteData.Values["controller"];
    var area = (string)ViewContext.RouteData.Values["area"];
    
    var dis = controller == "Users" ? "disabled" : "";
    
}

<nav class="navbar navbar-expand-lg" style="background-color: lightsteelblue">
    
    <div class="container-fluid justify-content-start">
        
        <div class="navbar-brand">Actions:</div>
        
        <a asp-area="@area" asp-action="Create" asp-controller="@controller" 
                id="createButton" class="navbar-btn btn btn-success mr-3 @dis">Create</a>
        
        <form method="post" asp-area="@area" asp-action="Edit" asp-controller="@controller"
              id="editButton">
            <button type="submit" class="navbar-btn btn btn-primary mr-3">Edit</button>
        </form>
        
        <form method="post" asp-area="@area" asp-action="Delete" asp-controller="@controller"
              id="deleteButton">
            <button type="submit" class="navbar-btn btn btn-danger mr-3">Delete</button>
        </form>

    </div>

</nav>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" style="background-color: powderblue">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Grasshoppers</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css"/>
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

    
</head>

<body>

<div class="wrapper">
    <iframe id="txtArea" style="display:none"></iframe>
    
    @await Html.PartialAsync("_SidebarPartial")

    <div id="content">

        <header>
            <nav class="navbar navbar-expand-lg navbar-dark">
                @if (User.Identity.IsAuthenticated)
                {
                    <div id="sidebarCollapse" class="mr-2" style="color: aliceblue">
                        <i class="fas fa-align-left"></i>
                    </div>
                }

                <a class="navbar-brand" asp-area="" asp-action="Index" asp-controller="Home">Grasshoppers</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <div class="navbar-nav mr-auto">
                        <a class="nav-link" asp-area="" asp-action="Index" asp-controller="Home">Who is online?</a>
                    </div>

                    @await Html.PartialAsync("_LoginPartial")

                </div>
            </nav>
        </header>

        <div class="container-fluid" style="background-color: powderblue">
            <partial name="_CookieConsentPartial"/>
            <main role="main" class="">
                @RenderBody()
            </main>
        </div>

    </div>

    <div class="overlay"></div>
</div>


<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
</environment>

<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="~/js/sidebar.js" asp-append-version="true"></script>
<script src="~/js/table.js" asp-append-version="true"></script>
<script src="~/js/actionbar.js" asp-append-version="true"></script>
<script src="~/js/report_action.js" asp-append-version="true"></script>

@RenderSection("Scripts", false)
</body>
</html>

Views/Shared/_PaginationPartial.cshtml
@model IPaginationViewModel

@{
    var prevHidden = !Model.HasPreviousPage ? "hidden" : "";
    var curHidden = !Model.HasPreviousPage && !Model.HasNextPage ? "hidden" : "";
    var nextHidden = !Model.HasNextPage ? "hidden" : "";
    
    var controller = (string)ViewContext.RouteData.Values["controller"];
    var area = (string)ViewContext.RouteData.Values["area"];
}

<ul class="pagination">
    <li class="page-item" @prevHidden>
        <a asp-area="@area" asp-controller="@controller" asp-action="Index"
           asp-route-page="@(Model.PageIndex - 1)"
           class="page-link">
            Previous
        </a>
    </li>
    <li class="page-item" @prevHidden>
        <a asp-area="@area" asp-controller="@controller" asp-action="Index"
           asp-route-page="@(Model.PageIndex - 1)"
           class="page-link">
            @(Model.PageIndex - 1)
        </a>
    </li>
             
    <li class="page-item" @curHidden>
        <a asp-area="@area" asp-controller="@controller" asp-action="Index"
           asp-route-page="@Model.PageIndex"
           class="page-link">
            @Model.PageIndex
        </a>
    </li>
             
    <li class="page-item" @nextHidden>
        <a asp-area="@area" asp-controller="@controller" asp-action="Index"
           asp-route-page="@(Model.PageIndex + 1)"
           class="page-link">
            @(Model.PageIndex + 1)
        </a>
    </li>
             
    <li class="page-item" @nextHidden>
        <a asp-area="@area" asp-controller="@controller" asp-action="Index"
           asp-route-page="@(Model.PageIndex + 1)"
           class="page-link">
            Next
        </a>
    </li>
</ul>

Views/Shared/_SidebarPartial.cshtml
@if (User.Identity.IsAuthenticated)
{
    <nav id="sidebar">
        <div id="dismiss">
            <i class="fas fa-arrow-left"></i>
        </div>

        <div class="sidebar-header">
            <p class="h5">What do you want to do?</p>
        </div>

        @if (User.IsInRole("admin"))
        {
            await Html.RenderPartialAsync("_AdminSidebarPartial");
        }
        
        @await Html.PartialAsync("_UserSidebarPartial")

    </nav>
}

Views/Shared/_SignUpPartial.cshtml
@model SignUpModel

<form method="post" asp-area="Identity" asp-controller="Account" asp-action="SignUp">

    <div class="form-group">
        <label asp-for="UserName"></label>
        <input asp-for="UserName" class="form-control" placeholder="Enter username" required/>
        <span asp-validation-for="UserName"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" placeholder="Enter email" required/>
        <span asp-validation-for="Email"></span>
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>

    <div class="form-group">
        <label asp-for="Password"></label>
        <input asp-for="Password" class="form-control" placeholder="Enter password" required/>
        <span asp-validation-for="Password"></span>
    </div>

    <div class="form-group">
        <label asp-for="PasswordConfirm"></label>
        <input asp-for="PasswordConfirm" class="form-control" placeholder="Enter password again" required/>
        <span asp-validation-for="PasswordConfirm"></span>
    </div>

    <button type="submit" class="form-control btn-lg btn-success">Sign up for Grasshoppers</button>
</form>

Views/Shared/_UserSidebarPartial.cshtml
<ul class="list-unstyled components">
    <li>
        <a href="#">My characters</a>
    </li>
    <li>
        <a href="#queriesSubmenu" data-toggle="collapse" aria-expanded="false">Queries</a>
        <ul class="collapse list-unstyled" id="queriesSubmenu">
            <li>
                <a href="#">My stats</a>
            </li>
            
            <li>
                <a href="#">Character's inventory...</a>
            </li>
            <li>
                <a href="#">The most played mission</a>
            </li>
            <li>
                <a href="#">The best character of the game session...</a>
            </li>
            <li>
                <a href="#">List of characters that have got the item...</a>
            </li>
            <li>
                <a href="#">Bounty hunter character</a>
            </li>
            <li>
                <a href="#">The fastest winner team</a>
            </li>
            <li>
                <a href="#">The best flag invader</a>
            </li>
        </ul>
    </li>
</ul>